version: '3.9'

services:
  redis:
    image: redis:6-bullseye
    container_name: redis_broker_develop
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    env_file:
      - .env
    healthcheck:
      test: ["CMD","redis-cli","ping"]

  postgres:
    image: postgres:14-bullseye
    container_name: postgres_db_develop
    environment:
    - POSTGRES_USER=${POSTGRES_DEVELOP_DB_USERNAME}
    - POSTGRES_PASSWORD=${POSTGRES_DEVELOP_DB_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DEVELOP_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  mongo:
    image: mongo:5
    container_name: mongo_db_develop
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - '27017:27017'

  mysql:
    image: mysql:8.0.32
    container_name: mysql_db_develop
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_DATABASE=${MYSQL_DEVELOP_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_DEVELOP_ROOT_PASSWORD}
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq_broker:stable
    hostname: rabbitmq_broker_develop
    container_name: rabbitmq_broker_develop
    environment:
    - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEVELOP_DEFAULT_USER}'
    - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEVELOP_DEFAULT_PASS}'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
    - '5672:5672'
    - '15672:15672'