version: '3.9'

services:
  brocker:
    image: redis:6-bullseye
    container_name: redis_broker_develop
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    env_file:
      - .env
    healthcheck:
      test: ["CMD","redis-cli","ping"]

  db:
    image: postgres:14-bullseye
    container_name: postgres_db_develop
    environment:
    - POSTGRES_USER=${POSTGRES_DEVELOP_DB_USERNAME}
    - POSTGRES_PASSWORD=${POSTGRES_DEVELOP_DB_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DEVELOP_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'