version: '3.9'

services:
  brocker:
    image: redis:6-bullseye
    container_name: redis_broker
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    env_file:
      - .env
    healthcheck:
      test: ["CMD","redis-cli","ping"]

  db:
    image: postgres:14-bullseye
    environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypassword
    - POSTGRES_DB=test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'